config/routes.rb
RorCms::Application.routes.draw do
  
  get "index/index"

  match '/activate/:user_id/:activation_key' => 'users#confirm_email', :constraint => {:user_id => /\d+/,:activation_key => /\w{40}/}, :as => :activate_account

  resources :users

  namespace "admin" do
    resources :index
    resources :roles
    root :to => 'index#index'
  end
  
  match '/admin' => 'admin/index#index', :as => :main_admin

  root :to => 'index#index', :as => :main

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, :dependent => :restrict

  validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 255 }
  validates :description, :length => { :maximum => 255 }
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  STATE_ACTIVE = 'A'
  STATE_NONACTIVE = 'N'

  belongs_to :role

  before_create :generate_activation_key, :set_state

  validates :email, :presence => true, :uniqueness => true
  validates :password, :confirmation => true

  validate :password_must_be_present

  attr_accessor :password_confirmation
  attr_reader :password

  def User.encrypt_pass(password, salt)
    Digest::SHA2.hexdigest(password + '^&*678' + salt)
  end

  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.pass = self.class.encrypt_pass(password, salt)
    end
  end

  private

		def generate_salt
			self.salt = self.object_id.to_s + rand.to_s
		end

		def password_must_be_present
			errors.add(:password, "Missing password") unless pass.present?
    end

    def generate_activation_key
      self.activation_key = Digest::SHA1.hexdigest(rand.to_s)
    end

    def set_state
      self.state = self.class::STATE_NONACTIVE
    end

end

app/controllers/admin/index_controller.rb
class Admin::IndexController < ApplicationController
  def index
    @some_val = 'fwefwefwe'
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < AdminController
  
  def index
    @roles = Role.all
    
    respond_to do |format|
      format.html
    end
  end
  
  def new
    @role = Role.new
    
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @role = Role.new(params[:role])
    
    respond_to do |format|
      if @role.save
        format.html { redirect_to([:admin, @role], :notice => "Role was added.") }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    
    respond_to do |format|
      format.html { redirect_to admin_roles_url}
    end
  end
  
  def edit
    @role = Role.find(params[:id])
  end
  
  def update
    @role = Role.find(params[:id])
    
    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to([:admin, @role], :notice => "Role was updated") }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def show
    @role = Role.find(params[:id])
    
    respond_to do |format|
      format.html
    end
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @user = User.new(params[:user])
    @user.role = Role.first(:conditions => ['name = ?', 'user'])

    User.transaction do
      respond_to do |format|
        if @user.save
          Notifier.confirm_email(@user).deliver
          format.html {redirect_to(main_url, :notice => "Your are registered. Confirm your email.")}
        else
          format.html { render :action => 'new' }
        end
      end
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def show
  end

  def confirm_email
    begin
      user = User.find(params[:user_id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Proba aktywacji uzytkownika o nieprawidlowym id #{params[:user_id]}"
      flash[:error] = 'Activation failed'
    else
      if user.activation_key != params[:activation_key]
        logger.error "Proba aktywacji uzytkownika o id #{params[:user_id]} nieprawidlowym kluczem = #{params[:activation_key]}"
        flash[:error] = 'Activation failed'
      else
        user.state = User::STATE_ACTIVE
        user.save
        flash[:notice] = 'Your acount is active. You can log in.'
      end
    end

    redirect_to main_url
  end

end

app/helpers/admin/index_helper.rb
module Admin::IndexHelper
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index/index.html.erb
<%= link_to "test", main_admin_path %>--

app/views/admin/roles/_form.html.erb
<%= form_for([:admin, @role]) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end%>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Edycja</h1>
<%= render 'form' %>

app/views/admin/roles/index.html.erb
<table>
	<tr>
		<th>Nazwa</th>
		<th>Opis</th>
	</tr>
	<% @roles.each do |role|%>
		<tr>
			<td><%= role.name %></td>
			<td><%= role.description %></td>
			<td><%= link_to 'Edit', edit_admin_role_path(role) %></td>
      <td><%= link_to 'Delete', [:admin, role], :confirm => 'Are you sure?', :method => :delete%></td>
		</tr>
	<% end %>
</table>
<%= link_to 'Nowa rola', new_admin_role_path %>

app/views/admin/roles/new.html.erb
<h1>Nowa rola</h1>
<%= render 'form' %>

app/views/admin/roles/show.html.erb
<p>
  <b>Name: </b>
  <%= @role.name %>
</p>
<p>
  <b>Description: </b>
  <%= @role.description %>
</p>

app/views/admin/shared/_menu.html.erb
<div id="menu">
    <ul>
        <li><%= link_to 'Index', admin_index_index_path %></li>
        <li><%= link_to 'Roles', admin_roles_path %></li>
    </ul>
</div>

app/views/index/index.html.erb
<h1>Index#index</h1>
<p>Find me in app/views/index/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorCms</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="main">
  <div id="header">
    Header
  </div>
  <% if flash[:notice] %>
  <div id="flash_notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:error] %>
  <div id="flash_error"><%= flash[:error] %></div>
  <% end %>
  <div id="main_container">
    <div id="content">
        <%= yield %>
    </div>
    <%= render "admin/shared/menu" %>
  </div>
  <div id="footer">
    Footer
  </div>
</div>
</body>
</html>

app/views/notifier/confirm_email.text.erb
Confirmation link: <%= link_to "confirm", activate_account_url(:host => 'localhost', :user_id => @user.id, :activation_key => @user.activation_key) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Enter User Details</legend>

    <div>
      <%= f.label :email %><br />
      <%= f.email_field :email %>
    </div>

    <div>
      <%= f.label :password, 'Password' %><br />
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation, 'Confirm' %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  </fieldset>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Register</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>